version: '4'

services:
  car_insurance_frontend:
    container_name: car_insurance_frontend
    image: node:16
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - 3000:3000
    tty: true
    working_dir: /stefan/frontend/app
    command: >
      bash -c "npm start"
